### ISSUE TITLE
Failed to create block data VINE: Could not parse data

### ISSUE THREAD

**Issue by HydrolienF** [HydrolienF/Underilla#11]
Error to investigate. 
world_base have been pregenerated in 1.21.1 to avoid vines direction issues. 

[20:44:58 WARN]: [Underilla] Failed to create block data VINE: Could not parse data: minecraft:vine[west=true,east=false,up=false,south=false,down=false,north=false]
[20:44:58 WARN]: java.lang.IllegalArgumentException: Could not parse data: minecraft:vine[west=true,east=false,up=false,south=false,down=false,north=false]
[20:44:58 WARN]:        at org.bukkit.craftbukkit.block.data.CraftBlockData.createNewData(CraftBlockData.java:593)
[20:44:58 WARN]:        at org.bukkit.craftbukkit.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:568)
[20:44:58 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
[20:44:58 WARN]:        at org.bukkit.craftbukkit.block.data.CraftBlockData.newData(CraftBlockData.java:568)
[20:44:58 WARN]:        at org.bukkit.craftbukkit.CraftServer.createBlockData(CraftServer.java:2814)
[20:44:58 WARN]:        at org.bukkit.Bukkit.createBlockData(Bukkit.java:2481)
[20:44:58 WARN]:        at org.bukkit.Material.createBlockData(Material.java:4826)
[20:44:58 WARN]:        at Underilla-Spigot-1.6.3.jar//com.jkantrell.mc.underilla.spigot.impl.BukkitChunkReader.blockFromTag(BukkitChunkReader.java:43)
[20:44:58 WARN]:        at Underilla-Spigot-1.6.3.jar//com.jkantrell.mc.underilla.spigot.impl.BukkitChunkReader.blockFromTag(BukkitChunkReader.java:62)
[20:44:58 WARN]:        at Underilla-Spigot-1.6.3.jar//com.jkantrell.mc.underilla.core.reader.ChunkReader.blockAt(ChunkReader.java:51)
[20:44:58 WARN]:        at Underilla-Spigot-1.6.3.jar//com.jkantrell.mc.underilla.core.reader.Reader.blockAt(Reader.java:14)
[20:44:58 WARN]:        at Underilla-Spigot-1.6.3.jar//com.jkantrell.mc.underilla.core.generation.AbsoluteMerger.mergeLand(AbsoluteMerger.java:50)
[20:44:58 WARN]:        at Underilla-Spigot-1.6.3.jar//com.jkantrell.mc.underilla.core.generation.Generator.generateSurface(Generator.java:66)
[20:44:58 WARN]:        at Underilla-Spigot-1.6.3.jar//com.jkantrell.mc.underilla.spigot.generation.UnderillaChunkGenerator.generateSurface(UnderillaChunkGenerator.java:74)
[20:44:58 WARN]:        at org.bukkit.craftbukkit.generator.CustomChunkGenerator.buildSurface(CustomChunkGenerator.java:143)
[20:44:58 WARN]:        at net.minecraft.world.level.chunk.status.ChunkStatusTasks.generateSurface(ChunkStatusTasks.java:93)
[20:44:58 WARN]:        at net.minecraft.world.level.chunk.status.ChunkStep.apply(ChunkStep.java:65)
[20:44:58 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkUpgradeGenericStatusTask.run(ChunkUpgradeGenericStatusTask.java:98)
[20:44:58 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351)
[20:44:58 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118)
[20:44:58 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:312)
[20:44:58 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:50)
[20:44:58 WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:vine does not have property 'down' at position 57: ...uth=false,<--[HERE]

**Comment by HydrolienF** [comment]
This issue have been fixed with be16deb55390dcc89180e0a95650d474a1452108
